title: msun
email: gmchofen@gmail.com
description: >-
  msun_ related blog. msun_ programming, talks about gamedev, big posts, artworks.
  Everything that is somewhat related to msun_.
baseurl: ""
url: ""
github_username: msun-dev

# Build settings
theme: null
plugins:
  - jekyll-feed


defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

include: [_pages]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
